name: paymentsystem
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.16.1
  firebase_core: ^0.4.5
  firebase_database: ^3.1.6
  hive: ^1.4.4
  lottie: any
  provider: any
#  flashy_tab_bar: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/mastercard.png
    - assets/images/payanim.json

  fonts:
  - family: Fira
    fonts:
    - asset: assets/fonts/firesans.ttf

  - family: customIcons
    fonts:
    - asset: assets/fonts/custom.ttf

  - family: customIcon2
    fonts:
    - asset: assets/fonts/customs.ttf